# Generated by Django 4.0 on 2022-02-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TextModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='sort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='section',
            name='text',
        ),
        migrations.AddField(
            model_name='section',
            name='image',
            field=models.ManyToManyField(blank=True, related_name='section_image', to='backend.ImageModul'),
        ),
        migrations.AddField(
            model_name='section',
            name='text',
            field=models.ManyToManyField(blank=True, related_name='section_text', to='backend.TextModul'),
        ),
    ]
