# Generated by Django 4.0 on 2022-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_imagemodul_textmodul_section_sort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmodul',
            name='text_foreign',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
