# Generated by Django 4.0 on 2022-02-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_section_image_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='textimagemodul',
            name='link',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
