# Generated by Django 4.0 on 2022-02-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='short_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
