# Generated by Django 4.0 on 2022-02-25 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
