# Generated by Django 4.0 on 2022-03-16 12:49

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_gallery_product_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.get_servicegallery_filename)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('service', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_gallery', to='backend.service')),
            ],
        ),
    ]
