# Generated by Django 4.0 on 2022-03-16 13:22

import backend.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_servicegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=backend.models.get_bloggallery_filename)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('blog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blog_gallery', to='backend.blog')),
            ],
        ),
    ]
